In [7]:
import numpy as np
# Crear un array unidimensional
arr = np.array([1, 2, 3, 4, 5])
print("Array unidimensional:", arr)

matri = arr.reshape(5, 1)
print("Matriz 5x1:\n", matri)
matri2 = np.array([1, 2, 3, 4, 5, 6]).reshape(3, 2)
print("Matriz 3x2:\n", matri2)

#elevamos al cuadrado cada elemento
arr_cuadrado = arr ** 2
print("Array al cuadrado:", arr_cuadrado)

Array unidimensional: [1 2 3 4 5]
Matriz 5x1:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Matriz 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Array al cuadrado: [ 1  4  9 16 25]


In [8]:
# matriz aleatoria de 3x3
matriz_aleatoria = np.random.rand(3, 3)
print("Matriz aleatoria 3x3:\n", matriz_aleatoria)

Matriz aleatoria 3x3:
 [[0.16299617 0.88296613 0.04528748]
 [0.18204997 0.39991601 0.73039042]
 [0.26911283 0.60998544 0.13272366]]
